### ISSUE TITLE
Absolute extrusion mode issue

### ISSUE THREAD

**Issue by HanauHustle** [GeekDetour/BrickLayers#17]
I want to express a big thank you for developing and sharing this script. This feature is so exciting!

I am encountering a bug that, as far as I understand, is related to absolute extrusion mode. I analyzed the G-code line by line to identify the cause. When printing, for example, two walls, the script processes the inner wall first and moves it half a layer up—so far, so good. However, the extruder position for the outer wall then resumes with the extrusion value that it would have had after completing the inner wall. This results in a massive blob at the start of the outer wall extrusion.

I will add some lines of the gcode that show this. Please let me know if I can contribute any other info.

OS: Windows
Slicer: PrusaSlicer 2.9.1
Printer: Raise3D Pro3 Plus

[...]
**G1 X160.692 Y146.811 E0.00647 ; last extrusion of object 1**
; stop printing object LayerAdhesionSample.stl id:0 copy 0
**M82 ; BRICK: Return to Absolute Extrusion**
G92 E16.28336 ; BRICK: Resets the Extruder absolute position
G1 X152.615 Y140.849 F9000 ; BRICK: Calculated to next coordinate
G1 F900 ; BRICK: Feed Rate
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.5
**G92 E0**
G1 Z1.6 F300
;AFTER_LAYER_CHANGE
;LAYER:2
;Z:1.6
G1 X160.521 Y146.835 F9000
G1 X161.14 Y147.643 F9000 ; BRICK: Calculated to next coordinate
G1 F9000 ; BRICK: Feed Rate
M204 P500
;TYPE:External perimeter
;WIDTH:1.125
G1 F900
**G1 X160.794 Y147.895 E6.72339 ; Extruder pushes 6mm of filament**
[...]

**Comment by GeekDetour** [comment]
Thanks for posting this! And thanks for your excitement!

Indeed, the easiest way to do Brick Layers would be using ONLY relative extrusions - since we can freely re-adjust how much each line can push without having to update the 'absolute' value from all lines.

To support Absolute Extrusion, I did a dirty trick: for the inner walls I temporarily change to relative extrusion, output the adjusted walls, and after that, I move back to absolute extrusion (resetting it's 'odometer' to the value it should be at that point, so it can continue normally.

I didn't test so much with absolute extrusion - I might be doing some uncalculated detraction (or something else) before changing back to absolute, and it is creating a Blob.

Could you try "Relative Extrusion", so you could play with something that was more battle-tested?

**Comment by brad4edat** [comment]
I've been using the script as a test for a few weeks and so far I haven't had any problems.
But for two or three days, with both the old and new versions of the script, I've noticed that there are problems with some large objects for printing that have a very large pull of the filament back and then forward when changing the position of the extruder.
Instead of the specified 3-4mm. to pull the filament when changing the position of the extruder, it makes pulls of 30-40mm. at least! I don't know exactly how many. But it pulls the filament back a lot and then immediately brings it back forward again, but this is enough to clog the extruder and the nozzle.
For now, I haven't been able to find out what the problem is with the old or new code, but until recently, there were no problems with smaller objects and 5-6 hour prints. Now there are problems with large objects that are 10-25 hours per print, they start to appear even in the initial lines...

**Comment by GeekDetour** [comment]
@brad4edat It's true. There was a bug fix that actually turned the travel/retraction logic worse. 
I am working asap to make a better solution.
Thanks!!!

**Comment by brad4edat** [comment]
Hello. Thanks for the quick reply. So I should wait for the new bricklayers.py file to be updated and then download it again for testing.

Would you write a reply here when such a corrected file with the necessary correction is uploaded so I can download it for testing!?

Until recently it worked great and I printed several very healthy objects, but since these 2-3 days it has been absurd, it is pulling back a lot:)

Until now I have also tried to dig into the code after the slicer and in the python code itself but I did not have find the problem. My skills in code are not particularly good, although I have some. I am into hardware and wires :)

Kind regards
Nikola,
Bulgaria

**Comment by GeekDetour** [comment]
@brad4edat Absolutely - I'll mention you on a comment here when it is done. Thanks for caring!

**Comment by GeekDetour** [comment]
@brad4edat We are back :) I could fix some minor travel problems that I didn't have time before - I hope it works nice on your machine!

**Comment by brad4edat** [comment]
Hello! I will test these days and write the result. Now at least I remember where the problems were on the last two 3D prints and I will check again with the same prints.
I will give an answer how the situation is now!
Thanks.

**Comment by brad4edat** [comment]
Hello. I did a test today and things are better. There is no huge back and forth of the filament when 3D printing. Now the nozzle does not clog. With the old problem, in addition to the long movements of the filament, sometimes there were also short but very sharp movements, tearing the filament. Now I don't notice them, it seems they are gone.

The only thing I noticed today as a problem to refine is that sometimes there are omissions of retractions. The Z-lift of the extruder remains, but the pulling of the filament back is missing and this leads to strinings. Here it is a little to see why now it sometimes misses this.
The rest seems OK
I use Windows 10
Prusa Slicer 2.9
Python.

Regards
Brad4edat
:)

**Comment by GeekDetour** [comment]
Wow @brad4edat your comment shows me that you are looking VERY CLOSE at what the script is doing. You clearly turned on "travel, wipes, retractions and unretracts" at the preview.

Sure, in the last two days I was dedicated to fix these "invisibles" aspects of the print - most people are just looking if the part "looks" great in the preview. But you nailed it: actual good printing depends on these movements being all matched well.

I think we will have it really good. But it is taking time.

Today I implemented a header with useful information, that is attached in the beginning of the Gcode file. And later tonight I will finish generating an error_log.txt because helping people without it is being very difficult.

**Comment by brad4edat** [comment]
Hello. Good afternoon.
I have been printing mechanical parts and housings for measuring instruments for years. For me, the appearance is not a priority as much as the maximum strength of the 3D printed object itself. This is where this innovative way of printing shows its strength for me and my objects.

My printer has two stepper motors on the Z axis and this allows me to make quick lifts of the extruder and usually in 90% of cases I use such a lift combined with retraction.

That's why I noticed that in some places the reverse retraction of the filament is missing but the extruder continues to perform its "empty" lift and movement, without the filament being pulled, which leads to strinings... :))

I'm looking at the new codes these days when I have time and go to my machine in the workshop.

Regards
brad4edat

**Comment by brad4edat** [comment]
I saw that in another topic about the problem there was a comment about angular wetting of the object, on the edge where the sims are.

This way of printing is extremely important before each print to run at least 100mm. filament to check the extruder steps and calibrate them accurately. Feed 1.05 works best for me. This way the filaments are perfectly intertwined and the extruder does not "click" to reload from filament that has not come out of the nozzle from overflow.

Perfect checking and calibration before each print are very important, and it helps a lot to eliminate angular wetting of sims, by setting it to random, not aligned or on an edge. That is, it is desirable for sims to be in random places, so the object is printed without this wetting of the filament.

**Comment by GeekDetour** [comment]
@brad4edat I still need the time to do a very careful check on where I might no be retracting / unretracting perfectly at this point. But before, it looks like, the size the code got, in a single file, might be keeping other developers away from looking deeply at this.... or maybe bricklayers is too-niche. Don't know :)

**Comment by brad4edat** [comment]
I must report that problem with strange retraction still exist, and objects printing before nice, now have problems vith retractions. This long retractions make short james nozzle and objects have delaminations...
Situation is better from before but problem stil exist :)
Windows10
Prusa 2.6

Objects slice nice and look nice after chek in slicer, but problem with incorect retractions just     make objects to print very bad, delaminated...

:)  Will be soon new  bricklayerce file for test? :)
